var constants = { 
    DEFAULT_COLISSION_CATEGORY = 1,
    ORGANIC_COLLISION_CATEGORY = 2,
    GARBAGE_COLLISION_CATEGORY = 3,
    RECYCLING_COLLISION_CATEGORY = 4,
    ORGANIC_BIN_COLLISION_CATEGORY = 5,
    GARBAGE_BIN_COLLISION_CATEGORY = 6,
    RECYCLING_BIN_COLLISION_CATEGORY = 7,
}